server:
  port: -1  # Désactiver le serveur web Spring Boot (Camel/Jetty gère les routes)

spring:
  application:
    name: esb-central

patient:
  service:
    url: http://patient-core-service:8080

billing:
  service:
    url: http://billing-service:3000

logging:
  level:
    org.apache.camel: INFO
    com.novacare: DEBUG


